name = "email-classifier-agent"
main = "email-classifier-worker.js"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will be set via .dev.vars

[env.production]
# Production environment settings
